### ISSUE TITLE
IMessage interface mismatch

### ISSUE THREAD

**Issue by v-p-b** [cobbr/C2Bridge#2]
Code in this repository defined `IMessenger` as:

```cs
public interface IMessenger
{
    string Hostname { get; }
    string Identifier { get; set; }
    string Authenticator { get; set; }
    string Read();
    void Write(string Message);
    void Close();
}
```

However, Covenant expects `Read()` to return a custom object:

https://github.com/cobbr/Covenant/blob/master/Covenant/Data/Grunt/GruntBridge/GruntBridgeStager.cs#L61

https://github.com/cobbr/Covenant/blob/5b90f203c2e42c0f0e5607653c71f6fc452adaab/Covenant/Data/Profiles/DefaultBridgeProfile.yaml#L47

While this is easy to fix syntactically, it would be useful to know how the `ProfileMessage.Type` should be set (how it is indicated by communicating parties, etc.).

**Comment by v-p-b** [comment]
This property is also missing from the interface: 

```cs
EventHandler<MessageEventArgs> UpstreamEventHandler { get; set; }
```

https://github.com/cobbr/Covenant/blob/5b90f203c2e42c0f0e5607653c71f6fc452adaab/Covenant/Data/Profiles/DefaultBridgeProfile.yaml#L46

**Comment by cobbr** [comment]
Hey @v-p-b , apologies for the late response. Great catch, the interface needed to be updated after changes to Covenant.

This has been fixed in the current dev branch.
